### ISSUE TITLE
New Optional Extension TASKLISTITEMS to parse and generate HTML for GFM task list items

### ISSUE THREAD

**Issue by vsch** [sirthias/pegdown#185]
These are bullet lists of the form:

```markdown
* [ ] open task list
* [x] closed task list
```

And generates:

```html
<ul>
  <li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" disabled="disabled"></input>open task list</li>
  <li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" checked="checked" disabled="disabled"></input>closed task list</li>
</ul>
```

to look like:

* [ ] open task list
* [x] closed task list

provided the style sheet is provided to properly setup the list item generation and spacing.

The parser, ToHtmlSerializer and a new TaskListNode extending ListItemNode was added. New tests added to validate output when this extension is enabled and disabled. I will submit a PR with other fixes.

**NOTE: this is an optional extension not included in `Extensions.ALL`**
